title: Visual Studio Code と GitHub を活用したドキュメント編集
summary: |
  Visual Studio Code と GitHub を活用して複数人でドキュメントを作成・編集する方法についてまとめた本です。

  基本的にノンプログラマ・初心者向けの本になっています。とあるコミュニティのドキュメント制作用に書いた文章を Zenn で公開するために書き直しました。
  Visual Studio Code のインストール方法や基本的な使い方から始まり、GitHub の使い方、お勧めの拡張機能、運用方法などを解説しています。

  ドキュメントの管理者となる人よりも、ドキュメントを書く人向け寄りの本になっています。したがって、すでにオーガニゼーションやリポジトリが存在することを前提に解説しますので、もし無い場合は適宜作成してください。
topics: ['vscode', 'github', 'document']
published: false
price: 0
