name: Copilot Setup Steps

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: .node-version

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: package.json
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Validate environment setup
        run: |
          echo "Node.js version: $(node --version)"
          echo "pnpm version: $(pnpm --version)"
          echo "Checking if Zenn CLI is available..."
          pnpm exec zenn --help > /dev/null && echo "✓ Zenn CLI is available"
          echo "Checking if textlint is available..."
          pnpm exec textlint --version > /dev/null && echo "✓ textlint is available"
          echo "Running lint check to validate textlint configuration..."
          pnpm run lint
          echo "✓ Development environment setup completed successfully"